### ISSUE TITLE
Access to inexistent TIMEREC member in McuTimeDate and McuTimeDate_UnixSecondsToTimeDateCustom

### ISSUE THREAD

**Issue by tadibatt** [ErichStyger/McuOnEclipseLibrary#1]
I have found an error in the "McuTimeDate_ParseCommand" function.
If in the config the flag "McuTimeDate_HAS_SEC100_IN_TIMEREC" is set to "0" then the "TIMEREC" struct doesn't have the member "Sec100" so we need to change the line:
 time.Sec100 = 0;
to 
#if McuTimeDate_HAS_SEC100_IN_TIMEREC
        time.Sec100 = 0;
#endif

We need to do this also in the "McuTimeDate_UnixSecondsToTimeDateCustom" function.

**Comment by ErichStyger** [comment]
thanks for reporting!
Fixed in https://github.com/ErichStyger/McuOnEclipseLibrary/commit/73db99c7fb7c06c6d07e228af9da9766b4f44582
