### ISSUE TITLE
ERR_OK is conflicted with err.h in lwip

### ISSUE THREAD

**Issue by bjrobertshen** [ErichStyger/McuOnEclipseLibrary#2]
When I use McuLib with lwip, there is the ERR_OK conflict in err.h with lwip.  I changed ERR_OK with Mcu_ERR_OK in McuLib.h and change it in all files in Mculib and fix this conflict. Could we change ERR_OK to avoid conflict with other middleware?

**Comment by ErichStyger** [comment]
Are you using the lwip present in the McuLib? I fixed it with renaming all ERR_OK inside the lwip. That ERR_OK comes from legacy Processor Expert, and I have found it easier to fix lwip instead of changing all (more than 150) other middleware.

**Comment by bjrobertshen** [comment]
Got it. Thanks.
